---
pip:
  install:
    - httpie # better curl alternative
    - paramiko # ssh communication
    - pyftpdlib # create ftp servers from cmdline
    - requests # easy scripting of http requests
    - updog # python http server replacement that supports ssl & file upload
    - wsgidav # WebDAV server
    - git+https://github.com/Tib3rius/AutoRecon.git # autorecon scanner

apt:
  # check out many tools listed here: https://www.kali.org/tools/kali-meta/
  install:
    # - Paramspider
    # - amass
    # - anew
    # - anti-burl
    # - aquatone
    # - assetfinder
    # - dalfox
    # - default-libmysqlclient-dev
    # - dnsprobe
    # - dnsvalidator
    # - dotnet-sdk
    # - fbrobe
    # - gau
    # - getjs
    # - gf
    # - gowitness
    # - hakrawler
    # - httprobe
    # - kxss
    # - massdns
    # - monodevelop  # cross-platform .NET IDE
    # - mosh
    # - nodejs
    # - projectdiscovery chaos
    # - projectdiscovery chaos-client
    # - projectdiscovery httpx
    # - projectdiscovery naabu
    # - projectdiscovery nuclei
    # - projectdiscovery shuffledns
    # - sn0int
    # - subfinder
    # - subgen
    # - subjack
    # - urlprobe
    # - veil # shellcode obfuscation framework
    # - waybackurls
    # - zdns
    - beef-xss # browser exploitation framework
    - bettercap # wireless network attack tool
    - binwalk # analyze/extract binary files
    - bloodhound # graph analysis of Windows AD domains
    - build-essential # compiling tools, pwntools and pyenv dependency
    - burpsuite # web pentest framework
    - catdoc # text extractors for MS Office files
    - cewl # wordlist generator from URL spidering
    - chisel # HTTP tunnel, firewall evasion
    - crackmapexec # windows/AD pentest tools
    - crowbar # tool for ssh *key* brute forcing, keys at https://github.com/g0tmi1k/debian-ssh
    - default-mysql-client # MySQL database client
    - dirb # web directory brute-forcer
    - dsniff # sniff network traffic for cleartext insecurities
    - enum4linux # autorecon dependency
    - evil-winrm # Windows Remote Management shell
    - exploitdb # known exploit POCs
    - eyewitness # website snapshotting tool
    - feroxbuster # autorecon dependency
    - ffuf # autorecon dependency, web fuzzer
    - freerdp3-x11 # xfreerdp
    # - gcc-multilib # cross-compiling toolchains
    - gdb-peda # more friendly gdb display/commands
    - gobuster # autorecon dependency
    - hashcat # password (hash) cracking
    - hashcat-utils # standalone tools for advanced cracking with hashcat
    - hashid # figure out what hash type it is
    - hydra # password brute-forcing (over network)
    - john # password (hash) cracking
    - libc6:i386 # x86 GNU-libc
    - libffi-dev # pwntools dependency
    - libssl-dev # pwntools dependency
    - masscan # fast port scanner
    - metasploit-framework # exploit framework, hack all the things
    - mingw-w64 # dev environment for 32/64-bit windows
    - mitmproxy # machine-in-the-middle traffic
    - nbtscan # autorecon dependency, scans IP networks for NetBIOS name information
    - neo4j # bloodhound dependency, graph database
    - nikto # autorecon dependency
    - onesixtyone # autorecon dependency
    - oscanner # autorecon dependency, Oracle enumeration tool
    - patator # password brute-forcing (over network)
    - peass # privilege escalation awesome scripts suite
    - postgresql # database client/server, metasploit dependency
    - powercat # powershell implementation of netcat
    - powershell-empire # exploit framework
    - proxify # HTTP/HTTPS mitm tool
    - proxychains4 # proxy any TCP traffic over SOCKS
    - pure-ftpd # ftp server
    - python3-impacket # windows attack scripts
    - radare2 # RE toolchain (disassembly, debugging, patching, etc.)
    - rinetd # user-mode port redirection utility
    - rlwrap # add line wrapping to netcat shells
    - seclists # autorecon dependency
    # - shellter # AV-evasion by injecting malware into legit .exe
    - sipvicious # autorecon dependency, used to audit SIP-based VoIP systems
    - smbclient # autorecon dependency
    - smbmap # autorecon dependency
    - smtp-user-enum # autorecon dependency
    - snmp # autorecon dependency, includes snmpwalk
    - snmp-mibs-downloader # get latest SNMP MIBs
    - snmpcheck # like snmpwalk. nicely formatted snmp enumeration
    - sqlmap # SQL injection tool (AUTO-EXPLOITER, banned in OSCP)
    - sqsh # MS-SQL client
    - sshfs # mount file share over ssh
    - sshuttle # easy ssh tunnels
    - sslscan # autorecon dependency, audit SSL algorithms/cipher suites allowed
    - sslsniff # SSL/TLS machine-in-the-middle attack tool
    - tnscmd10g # autorecon dependency, tool to talk to Oracle TNS listener on port 1521/tcp
    - unix-privesc-check # tool to find privesc vulns in *nix systems
    - whatweb # autorecon dependency, recognize web technologies/plugins used by a site
    - windows-privesc-check # tool to find privesc vulns in windows
    - wine # windows API, lets you run windows binaries on linux
    - wkhtmltopdf # autorecon dependency, HTML to PDF rendering
    - wpscan # wordpress scanning tool
